---
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install packages
    apt:
      pkg:
        - apt-transport-https
        - nfs-common

  - name: Add the docker repo key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes
      filename: docker

  - name: Install docker
    apt:
      name: docker-ce
      state: present

  - name: Add {{ ansible_user }} user to docker group
    user:
      name: '{{ ansible_user }}'
      groups: docker
      append: yes

  - name: Install Hetrix heartbeat monitor
    ansible.builtin.cron:
      name: "hetrixtools heartbeat monitor"
      minute: "*/5"
      hour: "*"
      day: "*"
      month: "*"
      weekday: "*"
      job: "/usr/bin/curl --retry 3 --retry-delay 1 -m 15 https://sm.hetrixtools.net/hb/?s={{ hetrix_token }} >/dev/null 2>&1"
    when: hetrix_token is defined
